### ISSUE TITLE
Cannot resolve C++ toolchain

### ISSUE THREAD

**Issue by parisholley** [buildbuddy-io/buildbuddy-toolchain#1]
While resolving toolchains for target @bazel_tools//tools/build_defs/hash:sha256: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.

**Comment by siggisim** [comment]
Hey @parisholley! Thanks for filing this.

Are you kicking off the remote build from a Mac or Linux host? Bazel RBE doesn't currently support having a different local and remote execution platforms. We're not (yet) running Mac runners on our Cloud RBE, so if you're kicking off your build from a Mac - that's likely causing the issues you're seeing. We're working hard on getting Mac executors up and running.

If you're using a linux host and still getting these errors, I'd try using rbe_autconfig from the bazel-toolchain repo and see if you still get the same error. If not, we can probably pull some of that toolchain configuration into buildbuddy-toolchain:
https://releases.bazel.build/bazel-toolchains.html

For the timeout issue, if that's happening on a linux host - it's likely some large artifact is timing out while uploading. Bazel's default timeout for this is 60 seconds - you can override this with the flag `--remote_timeout=600`. This upload should likely only happen on your first run, and be cached after that.

Happy to help debug further if none of this helps!

**Comment by parisholley** [comment]
I'm on a Mac *sad face*
